# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lineroad',
        ),
        migrations.AlterField(
            model_name='video',
            name='tvname',
            field=models.FloatField(choices=[('爱奇艺', '爱奇艺'), ('优酷', '优酷'), ('乐视网', '乐视网'), ('腾讯视频', '腾讯视频'), ('土豆', '土豆'), ('搜狐视频', '搜狐视频'), ('56我乐', '56我乐'), ('KU6.com', 'KU6.com'), ('华数TV', '华数TV'), ('音悦Tai', '音悦Tai'), ('芒果TV', '芒果TV'), ('新浪视频', '新浪视频'), ('网易视频', '网易视频'), ('6.CN', '6.CN'), ('酷狗音乐', '酷狗音乐'), ('爆米花网', '爆米花网'), ('凤凰视频', '凤凰视频'), ('看看新闻', '看看新闻'), ('时光网', '时光网'), ('酷我音乐', '酷我音乐'), ('1905', '1905'), ('糖豆', '糖豆'), ('央视网', '央视网')], default='爱奇艺', max_length=20),
        ),
    ]
